name: Build ksud

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 获取 ksud 版本
      - name: Generate version
        id: ver
        run: |
          VERSION=$(git describe --tags --always --dirty)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # v3.0 的 ksud 目录在 ksu/userspace/daemon
      - name: Build ksud
        run: |
          cd ksu/userspace/daemon
          go mod tidy
          go build -ldflags "-X github.com/tiann/KernelSU/ksu/userspace/daemon.VERSION=${VERSION}" -o ksud .

      - name: Upload ksud